# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'
strategy:
  matrix:
    # Python27:
    #   python.version: '2.7'
    Python37:
      python.version: "3.7"
      gdal.bin: "release-1911-x64-gdal-2-3-0-mapserver-7-0-7.zip"
      gdal.libs: "release-1911-x64-gdal-2-3-0-mapserver-7-0-7-libs.zip"
      gdal.version: "2.3.0"

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- powershell: |
    Invoke-WebRequest http://download.gisinternals.com/sdk/downloads/$(gdal.bin) -OutFile gdalbin.zip
    Expand-Archive -Path gdalbin.zip -DestinationPath C:\gdal
    Invoke-WebRequest http://download.gisinternals.com/sdk/downloads/$(gdal.libs) -OutFile gdallibs.zip
    Expand-Archive -Path gdallibs.zip -DestinationPath C:\gdal

    # Prepend GDAL to the PATH
    $Env:PATH = "C:\\gdal;C:\\gdal\\bin;C:\\gdal\\data;C:\\gdal\\bin\\gdal\\apps;" + $Env:PATH

    # Copy GDAL librarys into .libs
    xcopy C:\gdal\bin\*.dll fiona\.libs\
    xcopy C:\gdal\*.rtf fiona\.libs\licenses\

    # Install module dependencies
    python -m pip install --upgrade pip
    pip install -r requirements-dev.txt

    # Build Fiona!
    python setup.py build_ext -IC:\\gdal\\include -lgdal_i -LC:\\gdal\\lib --gdalversion $(gdal.version) bdist_wheel

    # Install the wheel
    pip install --force-reinstall --ignore-installed (Get-ChildItem dist\*.whl | % { "$_" })

    # Move the build folder to ensure we're not importing it
    move fiona fiona.build

    # Run tests
    pip install --upgrade pytest pytest-azurepipelines
    python -m pytest -m "not iconv and not wheel"
  env:
    GDAL_DATA: "C:\\gdal\\bin\\gdal-data"
    PACKAGE_DATA: "1"  # Include GDAL libs in the wheel
    SSL_CERT_FILE: "C:\\gdal\\bin\\curl\\curl-ca-bundle.crt"
    CURL_CA_BUNDLE: "C:\\gdal\\bin\\curl\\curl-ca-bundle.crt"
  displayName: 'Build and test'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    contents: 'dist/**'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: Wheel