# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'
strategy:
  matrix:
    # Python27:
    #   python.version: '2.7'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    curl http://download.gisinternals.com/sdk/downloads/release-1911-x64-gdal-2-3-0-mapserver-7-0-7.zip --output gdalbin.zip
    7z x gdalbin.zip -oC:\gdal
    curl http://download.gisinternals.com/sdk/downloads/release-1911-x64-gdal-2-3-0-mapserver-7-0-7-libs.zip --output gdallibs.zip
    7z x gdallibs.zip -oC:\gdal

    set PATH=C:\\gdal;C:\\gdal\\bin;C:\\gdal\\data;C:\\gdal\\bin\\gdal\\apps;%PATH%
    set GDAL_DATA=C:\\gdal\\bin\\gdal-data
    set PACKAGE_DATA=1

    # copy gisinternal gdal librarys into .libs
    xcopy C:\gdal\bin\*.dll fiona\.libs\
    xcopy C:\gdal\*.rtf fiona\.libs\licenses\

    python -m pip install --upgrade pip
    python -m pip install -r requirements-dev.txt
    python setup.py build_ext -IC:\\gdal\\include -lgdal_i -LC:\\gdal\\lib --gdalversion 2.3.0 develop

    #pip install dist\Fiona-1.8.6-cp37-cp37m-win_amd64.whl
    #move fiona fiona.build

    python -m pytest -m "not iconv and not wheel"

  displayName: 'Install dependencies'

# - script: |
#     pip install --upgrade pytest pytest-azurepipelines
#     python -m pytest -m \"not iconv and not wheel\" --cov fiona --cov-report term-missing
#   displayName: 'pytest'
